Add wallet status check and remove useless module
usechain/go-usechain pull request #12
Opened 2018-11-30 07:35 UTC by lyszhang

2018-11-30 08:54 UTC, bufrr requested changes

2018-11-30 08:54 UTC, crasker commented on accounts/keystore/keystore.go
> +	defer ks.mu.RUnlock()
Using `ks.mu.Unlock()` here instead?

2018-11-30 09:22 UTC, lyszhang commented on accounts/keystore/keystore.go
> +	defer ks.mu.RUnlock()
The lock is sync.RWMutex , not the keystore's  lock

2018-11-30 11:11 UTC, koelzen approved these changes

2018-12-03 01:55 UTC, bufrr approved these changes

2018-12-03 02:02 UTC, ablozhou approved these changes

2018-12-03 02:03 UTC, merged